micronaut:
  application:
    name: newtrion
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://192.168.86.100:5432/food
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

#jdbc:
#  default:
#    packages-to-scan:
#      - 'com.innercirclesoftware'
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        show_sql: true
jpa:
  default:
    packages-to-scan:
      - 'com.innercirclesoftware'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true


#postgres:
#  reactive:
#    client:
#      port: 5432
#      host: 192.168.86.109
#      database: food
#      user: postgres
#      password: postgres
#      maxSize: 5